### ISSUE TITLE
[Suggestion] Change the simulator language

### ISSUE THREAD

**Issue by carVaba** [twostraws/ControlRoom#58] opened 2020-02-19 19:29 UTC
Consider adding an option to change the device language
https://nshipster.com/simctl/

**Comment by alladinian** [comment] 2020-02-19 22:34
This is already being discussed in #48

**Comment by davedelong** [comment] 2020-02-20 01:49
Yep, this is duplicate of #48. Thanks for filing the issue!

**Closed by davedelong** 2020-02-20 01:49 UTC
